[package]
name = "dumper"
version = "0.1.0"
edition = "2021"

[dependencies]
rsfw = { path = "../rsfw" }
rsf = { git = "https://github.com/krishpranav/ruststation.git" }

[target.'cfg(fw = "1100")'.dependencies]
rsf-1100 = { git = "https://github.com/krishpranav/ruststation.git" }