[package]
name = "dumper"
version = "0.1.0"
edition = "2021"

[dependencies]
rsfw = { path = "../rsfw" }
rsf = { version = "0.1.0", path = "../../kernel-framework" }

[target.'cfg(fw = "1100")'.dependencies]
ps4-1100 = { version = "0.1.0", path = "../../kernel-framework/ps4-1100" }